### PR TITLE
Refactor promise helpers to fix Interrupt with async code

### PR DESCRIPTION
**Pull request by mstoykov**
## What?

This changes the promise helpers so after grafana/k6#4017 async code and Interrupt will work.

## Why?

AbortingPromises seems to have not been used at all and just adds complexity. And `promises.New()` already does the remaining things needed to happen, so this can be merged even without grafana/k6#4017.

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have added tests for my changes
- [ ] I have commented on my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by mstoykov** [comment]
The failure seems to have nothing to do with this PR. it also happens in a scheduled test

**Review by ankur22 — APPROVED** [review]
LGTM

**Review by inancgumus — APPROVED** [review]
Thanks 👍

**Comment by mstoykov** [comment]
just FYI I don't have permissions to merge this, so if do it when you want

**Pull request merged**
