### PR TITLE
Add lock around storage.Dir touching the fs

### PR DESCRIPTION
**Pull request by mstoykov**

### CODE REVIEW

**Comment by mstoykov** [comment]
This was giving me race conditions if I compile with `-race` and run against some of the examples. 

This likely was because I haven't fixed them to use the new API so they were erroring really fast, but even so this new (or moved) lock should prevent any kind of races.

**Comment by inancgumus** [comment]
> This was giving me race conditions if I compile with `-race` and run against some of the examples.

Interesting. I've never seen a race condition error from this one. What does the stack trace look like?

**Comment by mstoykov** [comment]
```
Write at 0x00c0007ca030 by goroutine 50:---------] 10 VUs  00m01.5s/10m0s  00/50 shared iters
  github.com/grafana/xk6-browser/storage.(*Dir).Make()
      github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/storage/storage.go:41 +0x204
  github.com/grafana/xk6-browser/chromium.(*BrowserType).launch()
      github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/chromium/browser_type.go:156 +0x4e9
  github.com/grafana/xk6-browser/chromium.(*BrowserType).Launch()
      github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/chromium/browser_type.go:129 +0x2c5
  runtime.call32()
      runtime/asm_amd64.s:725 +0x48
  reflect.Value.Call()
      reflect/value.go:368 +0xc7
  github.com/dop251/goja.(*Runtime).wrapReflectFunc.func1()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/runtime.go:1980 +0x1f0
  github.com/dop251/goja.(*vm)._nativeCall()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/vm.go:3233 +0x36a
  github.com/dop251/goja.call.exec()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/vm.go:3205 +0x250
  github.com/dop251/goja.(*call).exec()
      <autogenerated>:1 +0x55
  github.com/dop251/goja.(*vm).run()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/vm.go:495 +0x189
  github.com/dop251/goja.(*baseJsFuncObject)._call()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/func.go:318 +0x84e
  github.com/dop251/goja.(*baseJsFuncObject).call()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/func.go:328 +0xdb
  github.com/dop251/goja.(*baseJsFuncObject).Call()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/func.go:280 +0x65
  github.com/dop251/goja.(*baseJsFuncObject).Call-fm()
      <autogenerated>:1 +0xae
  github.com/dop251/goja.AssertFunction.func1.1()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/runtime.go:2397 +0x12d
  github.com/dop251/goja.(*vm).try()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/vm.go:634 +0x390
  github.com/dop251/goja.(*Runtime).runWrapped()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/runtime.go:2441 +0xed
  github.com/dop251/goja.AssertFunction.func1()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/runtime.go:2396 +0x111
  go.k6.io/k6/js.(*VU).runFn.func2.1()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/js/runner.go:777 +0x85
  go.k6.io/k6/js/eventloop.(*EventLoop).Start()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/js/eventloop/eventloop.go:171 +0x27a
  go.k6.io/k6/js.(*VU).runFn.func2()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/js/runner.go:776 +0x186
  go.k6.io/k6/js/common.RunWithPanicCatching()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/js/common/util.go:86 +0xd0
  go.k6.io/k6/js.(*VU).runFn()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/js/runner.go:775 +0x564
  go.k6.io/k6/js.(*ActiveVU).RunOnce()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/js/runner.go:720 +0x97b
  go.k6.io/k6/lib/executor.getIterationRunner.func1()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/lib/executor/helpers.go:124 +0x7d
  go.k6.io/k6/lib/executor.SharedIterations.Run.func6()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/lib/executor/shared_iterations.go:258 +0x5be
  github.com/dop251/goja.(*call).exec()
      <autogenerated>:1 +0x55
  github.com/dop251/goja.(*vm).run()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/vm.go:495 +0x189
  github.com/dop251/goja.(*baseJsFuncObject)._call()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/func.go:318 +0x84e
  github.com/dop251/goja.(*baseJsFuncObject).call()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/func.go:328 +0xdb
  github.com/dop251/goja.(*baseJsFuncObject).Call()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/func.go:280 +0x65
  github.com/dop251/goja.(*baseJsFuncObject).Call-fm()
      <autogenerated>:1 +0xae
  github.com/dop251/goja.AssertFunction.func1.1()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/runtime.go:2397 +0x12d
  github.com/dop251/goja.(*vm).try()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/vm.go:634 +0x390
  github.com/dop251/goja.(*Runtime).runWrapped()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/runtime.go:2441 +0xed
  github.com/dop251/goja.AssertFunction.func1()
      github.com/dop251/goja@v0.0.0-20221003171542-5ea1285e6c91/runtime.go:2396 +0x111
  go.k6.io/k6/js.(*VU).runFn.func2.1()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/js/runner.go:777 +0x85
  go.k6.io/k6/js/eventloop.(*EventLoop).Start()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/js/eventloop/eventloop.go:171 +0x27a
  go.k6.io/k6/js.(*VU).runFn.func2()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/js/runner.go:776 +0x186
  go.k6.io/k6/js/common.RunWithPanicCatching()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/js/common/util.go:86 +0xd0
  go.k6.io/k6/js.(*VU).runFn()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/js/runner.go:775 +0x564
  go.k6.io/k6/js.(*ActiveVU).RunOnce()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/js/runner.go:720 +0x97b
  go.k6.io/k6/lib/executor.getIterationRunner.func1()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/lib/executor/helpers.go:124 +0x7d
  go.k6.io/k6/lib/executor.SharedIterations.Run.func6()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/lib/executor/shared_iterations.go:258 +0x5be
  go.k6.io/k6/lib/executor.SharedIterations.Run.func8()
      go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/lib/executor/shared_iterations.go:270 +0x58

Previous read at 0x00c0007ca030 by goroutine 66:
  github.com/grafana/xk6-browser/storage.(*Dir).Cleanup()
      github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/storage/storage.go:74 +0x12b
  github.com/grafana/xk6-browser/chromium.(*BrowserType).launch.func1.1()
      github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/chromium/browser_type.go:163 +0x4e
  runtime.deferreturn()
      runtime/panic.go:476 +0x32
  github.com/grafana/xk6-browser/chromium.(*BrowserType).launch.func2()
      github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/chromium/browser_type.go:173 +0x58
```

**Review by inancgumus — APPROVED** [review]

**Review by imiric — APPROVED** [review]
Makes sense, thanks! :+1:

**Pull request merged**
