### PR TITLE
Add new mobile devices

### PR DESCRIPTION
**Pull request by MatheusLemes5**
## What?

In this PR, new Android and iOS devices have been introduced

## Why?

To be able to emulate more current devices.

## Checklist

- [x] add new ios devices
- [x] add new android devices

## Related PR(s)/Issue(s)
https://github.com/grafana/xk6-browser/issues/123

### CODE REVIEW

**Review by lemesmatheusatlas — APPROVED** [review]

**Comment by MatheusLemes5** [comment]
@ankur22 @inancgumus Do you think this implementation of adding new devices makes sense? I added more devices to be able to conduct tests and extract Core Web Vitals metrics from more current devices.

**Comment by inancgumus** [comment]
Hi @MatheusLemes5, thanks for your contribution. The review process would be easier if you could provide a table (or anything like that) to compare for us to see whether the device definitions are accurate. Thanks.

**Comment by MatheusLemes5** [comment]
@inancgumus @ankur22 
First, I generated the user agents using AI. Now, I have made changes to include only the user agents that are listed in Chrome DevTools, ensuring greater accuracy. The user agents can be found in the requests made by the page after emulating the device.


image

**Comment by inancgumus** [comment]
Closing since we didn't get a response from the author for quite a long time.

**Pull request closed without merging**
