### PR TITLE
Remove the build github action

### PR DESCRIPTION
**Pull request by ankur22**
xk6-browser is now an experiment module within k6. This means that we no longer need to build a dedicated version of xk6-browser binary and anyone wishing to download a pre-built binary should head over to the release section of the k6 repo.

### CODE REVIEW

**Comment by ka3de** [comment]
I think we can also remove the [build-release-sh](https://github.com/grafana/xk6-browser/blob/e7174062ccd51ddb19022a094663feca544fb999/build-release.sh) file as it was only referenced from the `build` GH action.

**Review by ka3de — APPROVED** [review]
LGTM.

**Review by inancgumus — COMMENTED** [review]
LGTM but why does it fail? :)

**Comment by ankur22** [comment]
> LGTM but why does it fail? :)

The fix for the build is in https://github.com/grafana/xk6-browser/pull/842.

**Review by inancgumus — APPROVED** [review]

**Pull request merged**
