### PR TITLE
Move all not implemented APIs to return promises

### PR DESCRIPTION
**Pull request by mstoykov**
Updates #428

### CODE REVIEW

**Comment by mstoykov** [comment]
This is just moving all the *not* implemetned APIs that return promises in playwright, to actually return promise and then change it everywhere.

This should *not* change anything for anyone but:
1. moves APIs from the interface so it makes it easier to know what more needs to be refactored
2. if somebody decides to implement those they will know they need to return a promise.

**Review by imiric — APPROVED** [review]
Seems reasonable :+1:

Good luck adding comments for all of them :sweat_smile:

**Review by ankur22 — APPROVED** [review]

**Comment by mstoykov** [comment]
I decide against writign proper documentation for 20+ methods ;).

I also will wait on #583 to merge this and squash it as long as nobody wants *proper* documentaiton

**Review by inancgumus — APPROVED** [review]

**Comment by inancgumus** [comment]
#566 [happened](https://github.com/grafana/xk6-browser/actions/runs/3235359073/jobs/5299674425) :(

**Comment by imiric** [comment]
@inancgumus #559 also happened in that run. Until this happens in an environment outside of CI, I'm still blaming GitHub Actions for it. But feel free to look into it if you want.

**Pull request merged**
