### PR TITLE
Remove unimplemented apis

### PR DESCRIPTION
**Pull request by ankur22**
## What?

Removing the unimplemented API function bodies.

## Why?

It's confusing when auditing APIs to have some that do not have any implementation. It's as if they are a priority, which is not the case. We will add the APIs that we think we need and when the community asks for them.

## Checklist

- [x] I have performed a self-review of my code
- [ ] I have added tests for my changes
- [ ] I have commented on my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by allansson — CHANGES_REQUESTED** [review]
I've built and run the extension and it works normally. 

It's hard to test that something isn't there, but looking at the code I don't see any methods removed that have an implementation and there would definitely be a build error if some reference was left.

I did however find three other methods that don't have an implementation:

- https://github.com/grafana/xk6-browser/blob/a53651b8f89867bcb7ed5354ceb587e3f9ac1fd5/common/browser_context.go#L261
- https://github.com/grafana/xk6-browser/blob/a53651b8f89867bcb7ed5354ceb587e3f9ac1fd5/chromium/browser_type.go#L220
- https://github.com/grafana/xk6-browser/blob/a53651b8f89867bcb7ed5354ceb587e3f9ac1fd5/common/page.go#L820

I'm sure if there's a reason why these should remain, but I just wanted to point it out.

**Comment by inancgumus** [comment]
👍 

> setExtraHTTPHeaders and LaunchPersistentContext

It seems safe to remove these ones.

> goBack

@ankur22 probably hasn't removed `goBack` because [this test](https://github.com/grafana/xk6-browser/blob/a53651b8f89867bcb7ed5354ceb587e3f9ac1fd5/tests/browser_test.go#L270-L314) requires it. However, we can easily implement an _undocumented_ method that panics. And then we can remove `GoBack`.

**Comment by ankur22** [comment]
> setExtraHTTPHeaders and LaunchPersistentContext

Yep, good spot, I've removed them in 4a2e5848318014e0f36c57cb83b73630ed22f1db.

> goBack

As @inancgumus mentioned it was indeed due to the `goback` method, but I've removed that now and changed the test in f9d21900e843fc233ba572f362b7cb51ddb0445c to still behave in the same way (apart from creating the browserContext and page first).

**Review by inancgumus — APPROVED** [review]

**Review by allansson — APPROVED** [review]
👍

**Pull request merged**
